baseURL = "https://shimakaze-git.github.io/"
languageCode = "ja-jp"
defaultContentLanguage = "ja-jp"
title = "shimakaze_soft Profile"
hasCJKLanguage = true
mainSections = ["posts"]

# theme = "athena"
theme = "hugo-theme-notrack"
# theme = "hugo-clarity"

[params]
description = "shimakaze_softのプロフィールページ"
dateform = "2006-1-2"
disable_next_prev = true
github_repo = "shimakaze-git.github.io"
github_username = "shimakaze-git"
