baseURL = "https://shimakaze-git.github.io/"
title = "shimakaze_soft profile"
theme = "hugo-theme-notrack"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
mainSections = ["posts"]

